[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
rustyscript = "0.12.3"
# https://github.com/rscarson/rustyscript/issues/399
serde = "=1.0.219"
serde_json = "=1.0.120"
serde_bytes = "=0.11.15"


[profile.release]
strip = true
opt-level = "z"
lto = true
